#!/usr/bin/env node
/**
 * Regenerate a data-only D1 seed file from a live environment's catalog.
 *
 * Purpose: make local dev mirror dev/prod instead of maintaining a parallel
 * hand-written catalog. After the pipeline runs (ETL → enrich → image-sync)
 * against dev, dump the enriched catalog here so `data/d1/seed.sql` — what
 * `npm run dev` / `preview:dev` load locally — matches what the deployed env
 * actually serves.
 *
 * Uses `wrangler d1 export --no-schema` (schema comes from migrations, so the
 * seed is INSERTs only) for a fixed set of catalog/content tables, in FK-safe
 * dependency order. Writes a generated-header banner so nobody hand-edits it.
 *
 * Usage:
 *   node scripts/db-dump.mjs --env dev                     # dev → data/d1/seed.sql
 *   node scripts/db-dump.mjs --env production --out /tmp/prod.sql
 *   node scripts/db-dump.mjs --env dev --local
 *
 * NOTE: this mirrors the target catalog verbatim, including its category model.
 * Decide category curation (see data/enrichment/) BEFORE pointing local at an
 * env whose categories you don't want as the canonical set.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, rmSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DB = "beauteas-db-dev"; // binding name; --env selects the real DB
// FK-safe dependency order (parents before children).
const TABLES = ["categories", "products", "product_variants", "pricing", "pages", "admin_settings"];
const tag = "[db:dump]";

function parseArgs() {
  const a = process.argv.slice(2);
  const env = (a[a.indexOf("--env") + 1] || "").trim();
  const outIdx = a.indexOf("--out");
  return {
    env,
    local: a.includes("--local"),
    out: outIdx >= 0 ? a[outIdx + 1] : join(ROOT, "data/d1/seed.sql"),
  };
}
const { env, local, out } = parseArgs();
if (env !== "dev" && env !== "production") {
  console.error(`${tag} ERROR: pass --env dev|production`);
  process.exit(1);
}
const scope = local ? "--local" : "--remote";

function wrangler(args) {
  execFileSync("npx", ["wrangler", ...args], { cwd: ROOT, stdio: ["ignore", "ignore", "inherit"] });
}

const tmp = join(ROOT, ".wrangler", `_dump-${env}.sql`);
const tableArgs = TABLES.flatMap((t) => ["--table", t]);
console.log(`${tag} exporting ${TABLES.length} tables from ${env} (${scope})...`);
wrangler(["d1", "export", DB, scope, "--env", env, "--no-schema", ...tableArgs, "--output", tmp]);

// Drop wrangler's PRAGMA/BEGIN noise; keep only the INSERTs, add a banner.
// Emit INSERT OR REPLACE so the seed is idempotent and coexists with rows that
// migrations already seed (e.g. the gift-card product from 0010_add_gift_cards).
const raw = readFileSync(tmp, "utf8");
const inserts = raw
  .split("\n")
  .filter((l) => l.trim().startsWith("INSERT INTO"))
  .map((l) => l.replace(/^INSERT INTO/, "INSERT OR REPLACE INTO"))
  .join("\n");
rmSync(tmp, { force: true });

const banner =
  `-- GENERATED by scripts/db-dump.mjs — do not edit by hand.\n` +
  `-- Data-only snapshot of the '${env}' catalog (schema comes from migrations/).\n` +
  `-- Tables: ${TABLES.join(", ")}\n` +
  `-- Regenerate: node scripts/db-dump.mjs --env ${env}\n\n` +
  `PRAGMA defer_foreign_keys=TRUE;\n\n`;

writeFileSync(out, banner + inserts + "\n");
const rows = inserts.split("\n").filter(Boolean).length;
console.log(`${tag} wrote ${rows} INSERT row(s) → ${out}`);
